### ISSUE TITLE
Let's add prettier?

### ISSUE THREAD

**Issue by demensky** [recksjs/recks#3]
I was very interested in this project. Do you mind if I add [.editorconfig](https://editorconfig.org/) and [prettier](https://prettier.io/) here?

**Comment by kosich** [comment]
🙂
Hi again, Dmitry! Yeah, let's add it!

Got a question regarding this:
What is the best way to ensure prettier has been run before pushing to remote?
Maybe we should add some git hook to do that?

**Comment by demensky** [comment]
For automation I usually use [_husky_ and _lint-staged_](https://prettier.io/docs/en/precommit.html#option-1-lint-stagedhttpsgithubcomokonetlint-staged), I can do something like this here.

**Comment by demensky** [comment]
I can't configure bots and [GitHub Actions](https://github.com/features/actions).

**Comment by kosich** [comment]
> For automation I usually use husky and lint-staged, I can do something like this here.

I think we can start with husky/lint-staged to add prettifying on before commit, and later we'll investigate some CI (like GithubActions) checks.

Sounds ok?

**Comment by kosich** [comment]
Also, can we exclude .md files, so docs will be manually formatted?

I want to still have ability to fine-tune docs code examples

**Comment by demensky** [comment]
> Also, can we exclude .md files, so docs will be manually formatted?

Sure.

> I want to still have ability to fine-tune docs code examples

Do you want to exclude the [examples](https://github.com/recksjs/recks/tree/master/examples) folder?

**Comment by kosich** [comment]
I thought of maybe dropping/moving examples folder.
Please, exclude it for now too -- we'll figure out what to do with it later.
Thx!
